# Generated by Django 5.2.4 on 2025-07-02 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('desc', models.TextField()),
                ('prompt', models.CharField(blank=True, max_length=200, null=True)),
                ('CEG', models.FileField(blank=True, null=True, upload_to='')),
                ('competitors', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
