# Generated by Django 5.2.6 on 2025-09-16 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='prompt',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
