# Generated by Django 5.2.6 on 2025-09-16 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_captain_alter_event_prompt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='prompt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
