# Generated by Django 5.2.6 on 2026-08-19 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_team_remove_event_competitors_event_teams_teammember_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='captain',
        ),
    ]
