# Generated by Django 5.2.6 on 2026-08-19 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_remove_event_captain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='teams',
            field=models.ManyToManyField(related_name='event', to='events.team'),
        ),
    ]
