# Generated by Django 5.2.4 on 2025-07-08 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('location', models.CharField(max_length=35)),
                ('date', models.DateField()),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EventAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=35)),
                ('competitors', models.TextField()),
                ('placement', models.CharField(max_length=3)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='achievements.conference')),
                ('eventRef', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.event')),
            ],
        ),
    ]
