# Generated by Django 5.2.4 on 2025-07-06 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('location', models.CharField(max_length=35)),
                ('year', models.IntegerField()),
                ('competitors', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('competitors', models.TextField()),
                ('placement', models.CharField(max_length=3)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='achievements.conference')),
            ],
        ),
    ]
