# Generated by Django 5.2.6 on 2026-09-18 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0008_alter_event_teams'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('location', models.CharField(blank=True, max_length=35, null=True)),
                ('month', models.CharField(blank=True, max_length=10, null=True)),
                ('year', models.IntegerField()),
                ('overall_placement', models.CharField(blank=True, max_length=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=35)),
                ('competitors', models.TextField(blank=True, null=True)),
                ('placement', models.CharField(max_length=3)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='achievements.conference')),
                ('eventRef', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.event')),
            ],
        ),
    ]
