# Generated by Django 5.2.6 on 2026-09-06 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_member_strikes_strike'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='strikesNum',
            field=models.IntegerField(default=0),
        ),
    ]
