from sentence_transformers import SentenceTransformer, util

events = [
    {"name": "Animatronics", "tags": ["robotics", "engineering", "design"], "desc": "To address the annual design challenge, participants exhibit and demonstrate their knowledge of mechanical and control systems by creating an animatronic device with a specific purpose (i.e., communicate an idea, entertain, demonstrate a concept, etc.) that includes sound, lights, and an appropriate surrounding environment (a display)."},
    {"name": "Architectural Design", "tags": ["architecture", "design", "modeling"], "desc": "In response to the annual design challenge, participants develop a set of architectural plans and related materials, and construct both a physical and computer-generated model to accurately depict their design. Semifinalists deliver a presentation and participate in an interview."},
    {"name": "Audio Podcasting", "tags": ["media", "communication", "audio"], "desc": "Participants use digital audio technology to create original content for a podcast piece that addresses the annual theme. The podcast must feature high level storytelling techniques, voice acting, and folly sound effects; the full entry must include documentation of the podcast development process and elements. Semifinalists participate in an interview."},
    {"name": "Biotechnology Design", "tags": ["biotechnology", "science", "innovation"], "desc": "Participants select a contemporary biotechnology problem that addresses the annual theme and demonstrates understanding of the topic through documented research, the development of a solution, a display (including an optional model or prototype), and an effective multimedia presentation. Semifinalists deliver a presentation and participate in an interview."},
    {"name": "Board Game Design", "tags": ["game design", "creativity", "strategy"], "desc": "Participants develop, build, and package a board game that focuses on a subject of their choice. Creative packaging, and the instructions, pieces, and cards associated with the pilot game will be evaluated. Semifinalists set up the game, demonstrate how the game is played, explain the game's features, and discuss the design process."},
    {"name": "Chapter Team", "tags": ["leadership", "teamwork", "presentation"], "desc": "Participants take a parliamentary procedure test to qualify for the semifinal round of competition. Semifinalists conduct an opening ceremony, items of business, parliamentary actions, and a closing ceremony."},
    {"name": "Children's Stories", "tags": ["writing", "literature", "creativity"], "desc": "In response to the annual theme, participants create an illustrated children's story of artistic, instructional, and social value, and submit documentation related to the development of the physical storybook. Semifinalists read their story aloud and participate in an interview."},
    {"name": "Artificial Intelligence", "tags": ["programming", "software", "technology", "AI"], "desc": "Applying leadership and 21st century skills, participants demonstrate knowledge of artificial intelligence (AI) concepts, models, and best practices by completing a test to qualify for semifinals. Semifinalist teams solve an onsite problem(s) using a generative artificial intelligence (GenAI) tool. Completed solutions are objectively measured to determine the best solution for the stated problem."},
    {"name": "Cybersecurity", "tags": ["programming", "software", "technology", "AI"], "desc": "Applying leadership and 21st century skills, participants respond to a cybersecurity challenge by identifying a breach in computer security via “Capture the Flag” games. Areas of challenge might include exploit development, digital puzzles, cryptography, reverse engineering, binary analysis, mobile security, etc. Participants must accurately address a series of on-site problems within a specified, limited amount of time."},
    {"name": "Computer-Aided Design (CAD), Architecture", "tags": ["CAD", "architecture", "design"], "desc": "Participants use complex computer graphic skills, tools, and processes to respond to a design challenge in which they develop representations of architectural subjects, such as foundation and/or floor plans, and/or elevation drawings, and/or details of architectural ornamentation or cabinetry. The solution to the design challenge and participant answers in an interview are evaluated."},
    {"name": "Computer-Aided Design (CAD), Engineering", "tags": ["CAD", "engineering", "design"], "desc": "Participants use complex computer graphic skills, tools, and processes to respond to a design challenge in which they develop three-dimensional representations of engineering subjects, such as a machine part, tool, device, or manufactured product. The solution to the design challenge and participant answers in an interview are evaluated."},
    {"name": "Data Science and Analytics", "tags": ["data", "analysis", "statistics"], "desc": "Participants identify a societal issue, collect or compile data from various sources about the issue, and then produce documentation and a digital scientific poster about their findings. Semifinalists create a synopsis and digital visual representation of a data set provided in an onsite challenge."},
    {"name": "Debating Technological Issues", "tags": ["debate", "technology", "communication"], "desc": "Participants research the annual topic and subtopics and prepare for a debate against a team from another chapter. Teams are instructed to take either the pro or con side of a selected subtopic, submit a summary of references, and use their research to support their assigned position. The quality of a team's debate determines semifinalists and finalists."},
    {"name": "Digital Video Production", "tags": ["media", "video", "production"], "desc": "Participants develop and submit a digital video and a documentation portfolio (including such items as a storyboard, script, summary of references and sources, and equipment list) that reflects the annual theme. Semifinalists participate in an interview."},
    {"name": "Dragster Design", "tags": ["engineering", "design", "speed"], "desc": "Participants design, draw, and construct a CO2-powered dragster that adheres to specifications, design and documentation requirements, and the annual theme. Semifinalists compete in a double-elimination race and participate in an interview."},
    {"name": "Drone Challenge (UAV)", "tags": ["drone", "technology", "flight"], "desc": "Participants design, build, assemble, document, and test fly an open-source Unmanned Arial Vehicle (UAV) according to the stated annual theme/problem specifications. The required documentation portfolio must include elements such as a photographic log, wiring schematics, and a description of the programming software used. Semifinalists participate in an interview."},
    {"name": "Engineering Design", "tags": ["engineering", "design", "innovation"], "desc": "Participants develop a solution to an annual theme that is based on a specific challenge noted by the National Academy of Engineering (NAE) in its compilation of the grand challenges for engineering in the 21st century. The solution will include a documentation portfolio, a display, and a model/prototype. Semifinalists deliver a presentation and participate in an interview."},
    {"name": "Extemporaneous Speech", "tags": ["public speaking", "communication", "impromptu"], "desc": "Participants select a technology-related or TSA topic from among three topic cards and prepare and give a three-to-five-minute speech that communicates their knowledge of the chosen topic. The quality of the speech determines advancement to the semifinalist level of competition, for which an identical competition procedure is followed to determine finalists."},
    {"name": "Fashion Design and Technology", "tags": ["fashion", "design", "technology"], "desc": "To address the annual theme, participants demonstrate expertise in fashion design principles by creating a wearable garment, garment patterns, and a documentation portfolio. Semifinalist teams present their garment designs (worn by team models), discuss the design process with evaluators, and respond to interview questions."},
    {"name": "Flight Endurance", "tags": ["engineering", "flight", "design"], "desc": "Participants design, build, fly, and adjust (trim) a rubber-band powered model aircraft to make long endurance flights inside a contained airspace. Documentation (including elements such as attributes of the model design, drawings, and an analysis of the trim modifications), an inspection of the model and the required model flight box, and official times for two flights are aspects of the evaluation"},
    {"name": "Forensic Science", "tags": ["science", "investigation", "analysis"], "desc": "Participants take a test of basic forensic science to qualify for the semifinal round of competition. Semifinalists examine a mock crime scene and demonstrate their knowledge of forensic science through crime scene analysis, with the findings synthesized in a written report/analysis."},
    {"name": "Future Technology Teacher", "tags": ["education", "technology", "presentation"], "desc": "Participants research a developing technology, prepare a video showing an application of the technology in the classroom, and create a lesson plan/activity that features the application and connects to the Standards for Technological and Engineering Literacy (STEL), as well as STEM initiatives and integration. Semifinalists demonstrate the lesson plan and answer questions about their presentation."},
    {"name": "Manufacturing Prototype", "tags": ["manufacturing", "design", "prototype"], "desc": "Participants design, fabricate, and use Computer Integrated Manufacturing (CIM) to create a product that addresses the annual theme. A documentation portfolio and the completed product prototype are submitted for evaluation. Semifinalists give a product “sales pitch” and demonstration."},
    {"name": "Music Production", "tags": ["music", "production", "audio"], "desc": "Participants produce an original musical piece that reﬂects the annual theme on the TSA website under Themes & Problems. The quality of the musical piece and required documentation (including elements such as a plan of work, self-evaluation, and a list of hardware, software, and instruments used) determines advancement to the semifinal level of competition, during which semifinalist participants are interviewed."},
    {"name": "On Demand Video", "tags": ["media", "video", "production"], "desc": "Once participants receive the challenge details (required criteria, such as props and a line of dialogue) at the national TSA conference, they have 36 hours to produce a 60-second film that showcases video skills, tools, and communication processes. The quality of the completed video production determines the finalists."},
    {"name": "Photographic Technology", "tags": ["photography", "technology", "media"], "desc": "Participants produce a photographic portfolio - demonstrating expertise in photo and imaging technology processes - to convey a message based on the annual theme. Semifinalists have 24 hours to complete a portfolio of photos (with required documentation) taken onsite at the national TSA conference. Finalists are determined based on the quality of the semifinal portfolio, the portfolio presentation, and interview responses."},
    {"name": "Prepared Presentation", "tags": ["public speaking", "communication", "presentation"], "desc": "Participants deliver a three-to-five-minute oral presentation related to the current national TSA conference theme. Both semifinalists and finalists are determined based on the quality of the presentation and the appropriate use and content of the accompanying required slide deck."},
    {"name": "Promotional Design", "tags": ["design", "marketing", "creativity"], "desc": "Participants use computerized graphic communications layout and design skills to produce a promotional resource packet. The resource must address the annual theme/problem and include at least four printed publication items and required documentation. Semifinalists demonstrate publishing competency in an onsite technical design challenge."},
    {"name": "Robotics", "tags": ["robotics", "engineering", "technology"], "desc": "Participants design, build, document, and test a robot assembled using open-sourced parts according to stated specifications and to meet the challenge of the yearly theme/problem. "},
    {"name": "Hybrid Racer XL", "tags": ["engineering", "energy", "design"], "desc": "Hybrid Racer XL provides a hands-on opportunity for participants to apply science, technology, engineering, and mathematics (STEM) concepts - as well as leadership and 21st century skills such as creativity, teamwork, and problem-solving skills - as they design (according to annual requirements, if any), construct, and race a dual-powered (solar and battery) car."},
    {"name": "Software Development", "tags": ["programming", "software", "technology"], "desc": "Participants use their knowledge of cutting-edge technologies, algorithm design, problem-solving principles, effective communication, and collaboration to design, implement, test, document, and present a software development project of educational or social value. Both semifinalists and finalists are determined based on the quality of the presentation and project."},
    {"name": "STEM Mass Media", "tags": ["media", "STEM", "communication"], "desc": "In response to an annual theme, participants use written and verbal communication skills to convey a news story in both a video broadcast (preliminary round) and a digital written format (semifinal round). Participants must demonstrate a strong understanding of journalism etiquette and the common practices of the field of mass media."},
    {"name": "Structural Design and Engineering", "tags": ["engineering", "design", "construction"], "desc": "Participants apply the principles of structural engineering to design and construct a structure that complies with the annual challenge. An assessment of the required documentation and the destructive testing of the structure (to determine its design efficiency) determine both semifinalists and finalists."},
    {"name": "Automated Manufacturing Systems", "tags": ["technology", "automation", "engineering"], "desc": "Participants develop a solution to a problem (typically one from an industrial setting) presented onsite at the conference. They analyze the problem, build a computer-controlled mechanical model, program the model, demonstrate the programming and mechanical features of the model-solution in an interview, and provide instructions for evaluators to operate the model."},
    {"name": "Technology Bowl", "tags": ["knowledge", "technology", "competition"], "desc": "Participants demonstrate their knowledge of TSA and concepts addressed in technology content standards by completing an objective test. Semifinalist teams participate in a question/response, head-to-head, team competition."},
    {"name": "Technology Problem Solving", "tags": ["problem-solving", "technology", "innovation"], "desc": "Participants use problem-solving skills to design and construct a finite solution to a challenge provided onsite at the conference. Solutions are evaluated at the end of 90 minutes using measures appropriate to the challenge, such as elapsed time, horizontal or vertical distance, and/or strength."},
    {"name": "Transportation Modeling", "tags": ["transportation", "engineering", "modeling"], "desc": "Participants research, design, and produce a scale model of a vehicle that complies with the annual design problem. A display for the model and a documentation portfolio - containing elements such as a description of the vehicle, photographs and commentary detailing the vehicle production, and technical illustrations - are required. Semifinalists participate in an interview."},
    {"name": "Video Game Design", "tags": ["game design", "programming", "creativity"], "desc": "Participants design, build, and launch an E-rated online video game - with accompanying required documentation - that addresses the annual theme. Semifinalists participate in an interview to demonstrate the knowledge and expertise they gained during the development of the game."},
    {"name": "Virtual Reality Simulation (VR)", "tags": ["virtual reality", "technology", "simulation"], "desc": "Participants use video and 3D computer graphics tools and design processes to create a two-to-three-minute VR visualization (accompanied by supporting documentation) that addresses the annual theme. Semifinalists deliver a presentation about their visualization and participate in an interview."},
    {"name": "Webmaster", "tags": ["web development", "programming", "design"], "desc": "Participants design, build, and launch a website that addresses the annual challenge. Semifinalists participate in an interview to demonstrate the knowledge and expertise gained during the development of the website."},
    {"name": "Interior Design", "tags": ["architecture", "design", "modeling", "rennovation"], "desc": "Applying leadership and 21st century skills, participants develop a color sample and material design board(s) used by interior designers to plan an overall cohesive design based on an annual challenge. Participants must demonstrate an understanding of and aptitude for interior design, developing design boards, and presenting a design interpretation. "},
    {"name": "Vlogging", "tags": ["media", "video", "production", "vlog", "blog", "youtube", "content"], "desc": "Vlogging encourages good storytelling, videography, and editing techniques to create a coherent series of creative work. Applying leadership and 21st century skills, participants use digital video technology to create original content that reflects an annual technology theme. Semifinalists complete an onsite challenge to produce additional video(s). Required criteria, such as props, lines of dialog, topics, etc., will be revealed at the semifinalist orientation meeting."},
]

def get_event_description(event_name):
    for event in events:
        if event["name"] != event_name: continue
        return event["desc"]

model = SentenceTransformer('all-MiniLM-L6-v2')

# Encode event descriptions once
event_texts = [f"{e['name']}: {e['desc']} Tags: {', '.join(e['tags'])}" for e in events]
event_embeddings = model.encode(event_texts, convert_to_tensor=True)
def rank_events(prompt):
    query_embedding = model.encode(prompt, convert_to_tensor=True)
    scores = util.cos_sim(query_embedding, event_embeddings)[0]
    
    results = [(events[i]["name"], float(scores[i])) for i in range(len(events))]
    return sorted(results, key=lambda x: x[1], reverse=True)